quarkus.http.host=0.0.0.0
quarkus.http.port=8080
quarkus.swagger-ui.always-include=true
quarkus.log.console.format=%K{level}%d{HH:mm:ss.SSS} %-5p%K{clear} %s%e%n

quarkus.rabbitmq.devservices.enabled=false
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:admin}
rabbitmq-password=${RABBITMQ_PASSWORD:admin}

mp.messaging.incoming.ocr-processing.connector=smallrye-rabbitmq
mp.messaging.incoming.ocr-processing.queue.name=ocr-processing
mp.messaging.incoming.ocr-processing.exchange.name=ocr.processing
mp.messaging.incoming.ocr-processing.exchange.type=direct
mp.messaging.incoming.ocr-processing.exchange.declare=false
mp.messaging.incoming.ocr-processing.queue.declare=false
mp.messaging.incoming.ocr-processing.host=${rabbitmq-host}
mp.messaging.incoming.ocr-processing.port=${rabbitmq-port}
mp.messaging.incoming.ocr-processing.username=${rabbitmq-username}
mp.messaging.incoming.ocr-processing.password=${rabbitmq-password}

mp.messaging.outgoing.ocr-reading-return.connector=smallrye-rabbitmq
mp.messaging.outgoing.ocr-reading-return.exchange.name=ocr.reading
mp.messaging.outgoing.ocr-reading-return.exchange.type=direct
mp.messaging.outgoing.ocr-reading-return.exchange.declare=false
mp.messaging.outgoing.ocr-reading-return.default-routing-key=ocr.reading
mp.messaging.outgoing.ocr-reading-return.host=${rabbitmq-host}
mp.messaging.outgoing.ocr-reading-return.port=${rabbitmq-port}
mp.messaging.outgoing.ocr-reading-return.username=${rabbitmq-username}
mp.messaging.outgoing.ocr-reading-return.password=${rabbitmq-password}

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics
